name: QueryAPI
description: Query Information from other servers with ease

main: QueryAPI\Query
version: 1.0.1
api: [3.0.0]

author: Potatoe
website: https://github.com/PotatoeTrainYT/QueryAPI/
